# Generated by Django 2.0.6 on 2018-06-24 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0003_auto_20180624_1300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preparation_session',
            old_name='init_pids',
            new_name='initial_pids',
        ),
        migrations.RemoveField(
            model_name='preparation_session',
            name='init_slices',
        ),
    ]
