# Generated by Django 2.0.6 on 2018-06-24 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0004_auto_20180624_1302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preparation_session',
            old_name='initial_pids',
            new_name='num_initial_pids',
        ),
        migrations.AddField(
            model_name='preparation_session',
            name='num_target_features',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
