# Generated by Django 2.0.6 on 2018-06-27 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0005_auto_20180624_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model_Algorithm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Model_Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Training_Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_iteration', models.IntegerField()),
                ('model_algorithm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recommender.Model_Algorithm')),
                ('preparation_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recommender.Preparation_Session')),
            ],
        ),
        migrations.AddField(
            model_name='model_configuration',
            name='training_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recommender.Training_Session'),
        ),
    ]
