# Generated by Django 2.0.6 on 2018-06-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0006_auto_20180627_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='training_session',
            name='status',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
