# Generated by Django 2.0.6 on 2018-06-28 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0009_prediction_session_num_batch_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session_Meta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='prediction_session',
            name='meta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recommender.Session_Meta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preparation_session',
            name='meta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recommender.Session_Meta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='training_session',
            name='meta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recommender.Session_Meta'),
            preserve_default=False,
        ),
    ]
