# Generated by Django 2.0.6 on 2018-06-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0011_auto_20180628_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session_meta',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
