# Generated by Django 2.0.6 on 2018-07-14 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0012_auto_20180628_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model_configuration',
            name='training_session',
        ),
        migrations.DeleteModel(
            name='Model_Configuration',
        ),
    ]
