# Generated by Django 2.0.6 on 2018-07-14 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0013_auto_20180714_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model_Statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min', models.FloatField()),
                ('max', models.FloatField()),
                ('mean', models.FloatField()),
                ('average', models.FloatField()),
                ('training_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.Training_Session')),
            ],
        ),
    ]
