# Generated by Django 2.0.6 on 2018-07-14 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0014_model_statistic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model_statistic',
            name='average',
        ),
        migrations.RemoveField(
            model_name='model_statistic',
            name='max',
        ),
        migrations.RemoveField(
            model_name='model_statistic',
            name='mean',
        ),
        migrations.RemoveField(
            model_name='model_statistic',
            name='min',
        ),
    ]
