# Generated by Django 2.0.6 on 2018-07-14 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0015_auto_20180714_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_statistic',
            name='current_iteration',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='model_statistic',
            name='predict_average',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='model_statistic',
            name='predict_max',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='model_statistic',
            name='predict_mean',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='model_statistic',
            name='predict_min',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='model_statistic',
            name='train_average',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='model_statistic',
            name='train_max',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='model_statistic',
            name='train_mean',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='model_statistic',
            name='train_min',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
